# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac1aa60b0f5f0f9f0ab75656f231385bb3a82b41120934e092a70c3a9546c4501755270a0fb1dee14a4ffc71c9efd702aecd4f065ac9d792cc62070d441163e

test:
  secret_key_base: d15ebd700fa7224194be5d8cd8d072393935ef6ddc2226e8f77aead4fba53616c49b7a40aba644e6a907ad2f3862618f04c54b03ef2727d6568f60ab0198d216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
